# Generated by Django 5.2.7 on 2025-11-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes_autos'),
        ),
    ]
