# Generated by Django 5.2.7 on 2025-11-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='image',
            new_name='imagen',
        ),
    ]
